FROM node:4.4

LABEL maintainer Tano Iannetta <tano.iannetta@heig-vd.ch>
LABEL maintainer Loan Lassalle <loan.lassalle@heig-vd.ch>

RUN apt-get update && apt-get install -y vim

COPY src/ /opt/app

CMD ["node", "/opt/app/index.js"]
